m0_shoulder_left_joint:
  ID: 0
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 80
m1_shoulder_right_joint:
  ID: 1
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 80
m2_elbow_joint:
  ID: 2
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 40
m3_wrist_joint:
  ID: 3
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 60
m4_endeffector_joint:
  ID: 4
  Return_Delay_Time: 0
  Operating_Mode: 5
  Profile_Acceleration: 0
  Profile_Velocity: 50
m5_neck_joint:
  ID: 5
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 30
